spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/yong/app
    username: sa
    password:

decorator:
  datasource:
    p6spy:
      enable-logging: true
