spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-db/yong-test
    username: sa
    password:
    driver-class-name: org.h2.Driver
decorator:
  datasource:
    p6spy:
      enable-logging: true
