server:
  port: 9000

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  config: classpath:log4j2.yml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(??? ????), method(HTTP????)
    tags-sorter: alpha # ?? ?? ??
    path: /swagger-ui/index.html # html ?? ?? ??
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation ??? ??
  paths-to-match:
    - /**
