spring:
  datasource:
    url: jdbc:postgresql://db.advmzrtyhlmimuolvcrg.supabase.co:5432/postgres
    username: postgres
    password: yongcha123!
decorator:
  datasource:
    p6spy:
      enable-logging: true
